[tool.ruff]
line-length = 85
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check'
pre_format = 'ruff check --fix'
format = 'ruff format'
run = 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
pre_test = 'task lint'
test = '--disable-warnings --cov=app --cov-report=term-missing --verbose'
post_test = 'coverage html --directory=coverage'