"""Update models name

Revision ID: 08f98c5de922
Revises: ba34ef9597cb
Create Date: 2025-04-04 09:56:16.096872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08f98c5de922'
down_revision: Union[str, None] = 'ba34ef9597cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('materials', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('molds', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('operations', sa.Column('name', sa.VARCHAR(length=30), nullable=False))
    op.alter_column('parts', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parts', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('operations', 'name')
    op.alter_column('molds', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('materials', 'name',
               existing_type=sa.CHAR(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('machines', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
