"""Update table material_part

Revision ID: 0b91e75a528a
Revises: fc9858db3208
Create Date: 2025-04-29 21:20:37.938605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b91e75a528a'
down_revision: Union[str, None] = 'fc9858db3208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_part',
    sa.Column('material_id', sa.CHAR(length=36), nullable=False),
    sa.Column('part_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AVAILABLE', name='materialstatusenum'), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('material_id', 'part_id')
    )
    op.drop_table('material_parts')
    op.add_column('materials', sa.Column('lead_time', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'lead_time')
    op.create_table('material_parts',
    sa.Column('material_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('part_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'AVAILABLE'), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('disabled_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='material_parts_ibfk_1'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name='material_parts_ibfk_2'),
    sa.PrimaryKeyConstraint('material_id', 'part_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('material_part')
    # ### end Alembic commands ###
