"""create model_3d and nc_program models

Revision ID: 3bdc37653631
Revises: f43c42798139
Create Date: 2025-05-26 21:30:00.632103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bdc37653631'
down_revision: Union[str, None] = 'f43c42798139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_3d',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nc_programs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parts', sa.Column('model_3d_id', sa.CHAR(length=36), nullable=True))
    op.add_column('parts', sa.Column('nc_program_id', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'parts', 'models_3d', ['model_3d_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parts', 'nc_programs', ['nc_program_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parts', 'nc_program')
    op.drop_column('parts', 'model_3d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('model_3d', mysql.ENUM('PENDING', 'APPROVED'), nullable=False))
    op.add_column('parts', sa.Column('nc_program', mysql.ENUM('PENDING', 'APPROVED'), nullable=False))
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_column('parts', 'nc_program_id')
    op.drop_column('parts', 'model_3d_id')
    op.drop_table('nc_programs')
    op.drop_table('models_3d')
    # ### end Alembic commands ###
