"""Add id to material part

Revision ID: 4a9095c84d65
Revises: 0b91e75a528a
Create Date: 2025-04-29 21:48:28.494953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9095c84d65'
down_revision: Union[str, None] = '0b91e75a528a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_part', sa.Column('id', sa.CHAR(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_part', 'id')
    # ### end Alembic commands ###
