"""Create molds table

Revision ID: 5f5816e21a5e
Revises: ee1e7f77727b
Create Date: 2025-03-28 10:43:30.619799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5816e21a5e'
down_revision: Union[str, None] = 'ee1e7f77727b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molds',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SHIPPED', name='statusenum'), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.CHAR(length=36), nullable=True),
    sa.Column('customer_id', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimensions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molds')
    # ### end Alembic commands ###
