"""add atribute to all entities: disabled_at, is_active

Revision ID: c015fe072600
Revises: 16ee13b978d0
Create Date: 2025-03-26 21:12:40.482208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c015fe072600'
down_revision: Union[str, None] = '16ee13b978d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('customers', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled_at')
    op.drop_column('users', 'is_active')
    op.drop_column('customers', 'disabled_at')
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
