"""Add new tables and columns, update constraints, and remove 'cam_status' from parts.

Revision ID: c7abe39cb109
Revises: 0d593b93db8e
Create Date: 2025-04-03 12:55:16.961436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7abe39cb109'
down_revision: Union[str, None] = '0d593b93db8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('m_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNDER_MAINTENANCE', 'OUT_OF_SERVICE', name='machinestatusenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materials',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('op_type', sa.String(length=255), nullable=False),
    sa.Column('machine_id', sa.CHAR(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_association',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('Part', 'Mold', name='item_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='opstatusenum'), nullable=False),
    sa.Column('operation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_parts',
    sa.Column('material_id', sa.CHAR(length=36), nullable=False),
    sa.Column('part_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AVAILABLE', name='materialstatusenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('material_id', 'part_id')
    )
    op.alter_column('molds', 'dimensions',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index('dimensions', table_name='molds')
    op.create_unique_constraint(None, 'molds', ['name'])
    op.add_column('parts', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('parts', sa.Column('model_3d', sa.Enum('PENDING', 'APPROVED', name='simplestatusenum'), nullable=False))
    op.add_column('parts', sa.Column('nc_program', sa.Enum('PENDING', 'APPROVED', name='simplestatusenum'), nullable=False))
    op.create_unique_constraint(None, 'parts', ['name'])
    op.drop_column('parts', 'cam_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('cam_status', mysql.ENUM('PENDING', 'APPROVED'), nullable=False))
    op.drop_constraint(None, 'parts', type_='unique')
    op.drop_column('parts', 'nc_program')
    op.drop_column('parts', 'model_3d')
    op.drop_column('parts', 'description')
    op.drop_constraint(None, 'molds', type_='unique')
    op.create_index('dimensions', 'molds', ['dimensions'], unique=True)
    op.alter_column('molds', 'dimensions',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_table('material_parts')
    op.drop_table('operation_association')
    op.drop_table('operations')
    op.drop_table('materials')
    op.drop_table('machines')
    # ### end Alembic commands ###
