"""add progress_percentage to moldel

Revision ID: d640efc67fa0
Revises: 11b2f916c386
Create Date: 2025-05-09 19:43:12.427736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd640efc67fa0'
down_revision: Union[str, None] = '11b2f916c386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molds', sa.Column('priority_updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('molds', 'priority_updated_at')
    # ### end Alembic commands ###
