"""update atribute full_name of country not unique 

Revision ID: ee1e7f77727b
Revises: c015fe072600
Create Date: 2025-03-27 12:48:43.525457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1e7f77727b'
down_revision: Union[str, None] = 'c015fe072600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('full_name', table_name='customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('full_name', 'customers', ['full_name'], unique=True)
    # ### end Alembic commands ###
