"""update material name type

Revision ID: f42cf8fb1448
Revises: 3bdc37653631
Create Date: 2025-06-11 20:20:17.765879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f42cf8fb1448'
down_revision: Union[str, None] = '3bdc37653631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'name',
               existing_type=mysql.CHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
