name: Unit tests with Coveralls

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with Ruff
      run: ruff check .
      
    - name: Test with pytest
      run: |
        pytest --cov=app --cov-report=xml:coverage.xml
        
    - name: Check if coverage.xml exists
      run: |
        ls -l coverage.xml

    - name: Show contents of coverage.xml
      run: |
        cat coverage.xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        path-to-lcov: coverage.xml
